// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: game_logic.proto

package proto_game_logic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *GameInitRequest) Reset() {
	*x = GameInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInitRequest) ProtoMessage() {}

func (x *GameInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInitRequest.ProtoReflect.Descriptor instead.
func (*GameInitRequest) Descriptor() ([]byte, []int) {
	return file_game_logic_proto_rawDescGZIP(), []int{0}
}

func (x *GameInitRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GameInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId      string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameName    string `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameDesc    string `protobuf:"bytes,3,opt,name=game_desc,json=gameDesc,proto3" json:"game_desc,omitempty"`
	GameIcon    string `protobuf:"bytes,4,opt,name=game_icon,json=gameIcon,proto3" json:"game_icon,omitempty"`
	GameVersion string `protobuf:"bytes,5,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
}

func (x *GameInitResponse) Reset() {
	*x = GameInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInitResponse) ProtoMessage() {}

func (x *GameInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInitResponse.ProtoReflect.Descriptor instead.
func (*GameInitResponse) Descriptor() ([]byte, []int) {
	return file_game_logic_proto_rawDescGZIP(), []int{1}
}

func (x *GameInitResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameInitResponse) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *GameInitResponse) GetGameDesc() string {
	if x != nil {
		return x.GameDesc
	}
	return ""
}

func (x *GameInitResponse) GetGameIcon() string {
	if x != nil {
		return x.GameIcon
	}
	return ""
}

func (x *GameInitResponse) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

var File_game_logic_proto protoreflect.FileDescriptor

var file_game_logic_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0xa5,
	0x01, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x63, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x45, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x6f,
	0x67, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x10, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a,
	0x27, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_logic_proto_rawDescOnce sync.Once
	file_game_logic_proto_rawDescData = file_game_logic_proto_rawDesc
)

func file_game_logic_proto_rawDescGZIP() []byte {
	file_game_logic_proto_rawDescOnce.Do(func() {
		file_game_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_logic_proto_rawDescData)
	})
	return file_game_logic_proto_rawDescData
}

var file_game_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_logic_proto_goTypes = []interface{}{
	(*GameInitRequest)(nil),  // 0: GameInitRequest
	(*GameInitResponse)(nil), // 1: GameInitResponse
}
var file_game_logic_proto_depIdxs = []int32{
	0, // 0: GameLogicService.GameInit:input_type -> GameInitRequest
	1, // 1: GameLogicService.GameInit:output_type -> GameInitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_logic_proto_init() }
func file_game_logic_proto_init() {
	if File_game_logic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_logic_proto_goTypes,
		DependencyIndexes: file_game_logic_proto_depIdxs,
		MessageInfos:      file_game_logic_proto_msgTypes,
	}.Build()
	File_game_logic_proto = out.File
	file_game_logic_proto_rawDesc = nil
	file_game_logic_proto_goTypes = nil
	file_game_logic_proto_depIdxs = nil
}
